type TransactionDescription = {
    description: string
    type: string
}

export const transactionDescriptions : TransactionDescription[] = [
  { description: "[PO] Amazon.com Purchase", type: "Purchase" },
  { description: "[PO] Walmart Store #1234", type: "Debit Card Purchase" },
  { description: "[WD] ATM Withdrawal - TD Bank", type: "ATM Withdrawal" },
  { description: "[DD] Payroll Deposit - Acme Corp", type: "Direct Deposit" },
  { description: "[WT] Wire Transfer from John Smith", type: "Wire Transfer" },
  { description: "[PO] Starbucks #8765", type: "Purchase" },
  { description: "[PO] Shell Gas Station", type: "Debit Card Purchase" },
  { description: "[PM] Credit Card Payment - Chase", type: "Credit Card Payment" },
  { description: "[TR] Transfer to Savings Account", type: "Transfer" },
  { description: "[FE] Monthly Maintenance Fee", type: "Fee" },
  { description: "[IN] Interest Payment", type: "Interest" },
  { description: "[RF] Refund from Best Buy", type: "Refund" },
  { description: "[WD] Withdrawal - Branch Office", type: "Withdrawal" },
  { description: "[PO] Netflix Subscription", type: "Purchase" },
  { description: "[DD] Social Security Deposit - SSA", type: "Direct Deposit" },
  { description: "[PO] Target Store #5678", type: "Debit Card Purchase" },
  { description: "[WD] ATM Withdrawal - Bank of America", type: "ATM Withdrawal" },
  { description: "[TR] Transfer from Checking Account", type: "Transfer" },
  { description: "[PO] Uber Trip Payment", type: "Purchase" },
  { description: "[FE] Overdraft Fee", type: "Fee" },
  { description: "[PO] Apple iTunes Store", type: "Purchase" },
  { description: "[PO] McDonald's Restaurant", type: "Debit Card Purchase" },
  { description: "[DD] Payroll Deposit - Tech Solutions Inc", type: "Direct Deposit" },
  { description: "[PO] Home Depot #9876", type: "Purchase" },
  { description: "[WD] ATM Withdrawal - Wells Fargo", type: "ATM Withdrawal" },
  { description: "[PO] Costco Wholesale", type: "Debit Card Purchase" },
  { description: "[TR] Transfer to Checking Account", type: "Transfer" },
  { description: "[PO] Spotify Premium Subscription", type: "Purchase" },
  { description: "[RF] Refund from Macy's", type: "Refund" },
  { description: "[PO] CVS Pharmacy #4321", type: "Purchase" },
  { description: "[PM] Credit Card Payment - Discover", type: "Credit Card Payment" },
  { description: "[PO] Chipotle Mexican Grill", type: "Debit Card Purchase" },
  { description: "[DD] Direct Deposit - Freelance Payment", type: "Direct Deposit" },
  { description: "[WD] ATM Withdrawal - Citibank", type: "ATM Withdrawal" },
  { description: "[PO] Disney+ Subscription", type: "Purchase" },
  { description: "[FE] Wire Transfer Fee", type: "Fee" },
  { description: "[PO] Kroger Grocery Store", type: "Debit Card Purchase" },
  { description: "[WT] Wire Transfer from Sarah Johnson", type: "Wire Transfer" },
  { description: "[PO] Exxon Gas Station", type: "Purchase" },
  { description: "[IN] Savings Account Interest", type: "Interest" },
  { description: "[PO] Whole Foods Market", type: "Debit Card Purchase" },
  { description: "[TR] Transfer from Savings to Checking", type: "Transfer" },
  { description: "[PO] HBO Max Subscription", type: "Purchase" },
  { description: "[WD] Branch Withdrawal", type: "Withdrawal" },
  { description: "[PO] Lowe's Home Improvement", type: "Purchase" },
  { description: "[PM] Credit Card Payment - American Express", type: "Credit Card Payment" },
  { description: "[PO] Panera Bread", type: "Debit Card Purchase" },
  { description: "[DD] Tax Refund Deposit - IRS", type: "Direct Deposit" },
  { description: "[PO] Microsoft 365 Subscription", type: "Purchase" },
  { description: "[WD] ATM Withdrawal - PNC Bank", type: "ATM Withdrawal" },
  { description: "[RF] Refund from Nordstrom", type: "Refund" },
  { description: "[PO] Walgreens Pharmacy", type: "Debit Card Purchase" },
  { description: "[FE] ATM Foreign Transaction Fee", type: "Fee" },
  { description: "[PO] Dunkin Donuts", type: "Purchase" },
  { description: "[WT] Wire Transfer from David Lee", type: "Wire Transfer" },
  { description: "[PO] Safeway Grocery", type: "Debit Card Purchase" },
  { description: "[TR] Transfer to Money Market Account", type: "Transfer" },
  { description: "[PO] Adobe Creative Cloud", type: "Purchase" },
  { description: "[DD] Payroll Deposit - Global Enterprises", type: "Direct Deposit" },
  { description: "[PO] BP Gas Station", type: "Purchase" },
  { description: "[WD] ATM Withdrawal - US Bank", type: "ATM Withdrawal" },
  { description: "[PM] Credit Card Payment - Capital One", type: "Credit Card Payment" },
  { description: "[PO] Subway Restaurant", type: "Debit Card Purchase" },
  { description: "[IN] Checking Account Interest", type: "Interest" },
  { description: "[PO] GameStop Store", type: "Purchase" },
  { description: "[RF] Refund from Target", type: "Refund" },
  { description: "[PO] 7-Eleven Convenience Store", type: "Debit Card Purchase" },
  { description: "[FE] Insufficient Funds Fee", type: "Fee" },
  { description: "[PO] Hulu Subscription", type: "Purchase" },
  { description: "[WT] Wire Transfer from Emily Brown", type: "Wire Transfer" },
  { description: "[PO] Publix Super Market", type: "Purchase" },
  { description: "[WD] ATM Withdrawal - Capital One", type: "ATM Withdrawal" },
  { description: "[PO] Taco Bell", type: "Debit Card Purchase" },
  { description: "[TR] Transfer to Investment Account", type: "Transfer" },
  { description: "[DD] Rental Income Deposit", type: "Direct Deposit" },
  { description: "[PO] Barnes & Noble Bookstore", type: "Purchase" },
  { description: "[PM] Credit Card Payment - Citi", type: "Credit Card Payment" },
  { description: "[PO] Trader Joe's", type: "Debit Card Purchase" },
  { description: "[FE] Stop Payment Fee", type: "Fee" },
  { description: "[PO] Domino's Pizza", type: "Purchase" },
  { description: "[WD] ATM Withdrawal - Fifth Third Bank", type: "ATM Withdrawal" },
  { description: "[RF] Refund from Home Depot", type: "Refund" },
  { description: "[PO] Dollar General Store", type: "Debit Card Purchase" },
  { description: "[PO] YouTube Premium Subscription", type: "Purchase" },
  { description: "[WT] Wire Transfer from Michael Chen", type: "Wire Transfer" },
  { description: "[DD] Payroll Deposit - Financial Services Co", type: "Direct Deposit" },
  { description: "[PO] Rite Aid Pharmacy", type: "Purchase" },
  { description: "[TR] Transfer from Money Market", type: "Transfer" },
  { description: "[PO] Planet Fitness Membership", type: "Purchase" },
  { description: "[WD] ATM Withdrawal - Chase Bank", type: "ATM Withdrawal" },
  { description: "[PO] Pizza Hut", type: "Debit Card Purchase" },
  { description: "[IN] CD Interest Payment", type: "Interest" },
  { description: "[PM] Credit Card Payment - Bank of America", type: "Credit Card Payment" },
  { description: "[PO] Office Depot", type: "Purchase" },
  { description: "[FE] Paper Statement Fee", type: "Fee" },
  { description: "[PO] Kohl's Department Store", type: "Debit Card Purchase" },
  { description: "[DD] Dividend Deposit - Investment Fund", type: "Direct Deposit" },
  { description: "[RF] Refund from Walmart", type: "Refund" },
  { description: "[PO] Wendy's Restaurant", type: "Purchase" },
  { description: "[WD] ATM Withdrawal - Regions Bank", type: "ATM Withdrawal" },
  { description: "[PO] Sam's Club", type: "Debit Card Purchase" },
  { description: "[TR] Transfer to Emergency Fund", type: "Transfer" },
  { description: "[PO] Zoom Subscription", type: "Purchase" },
  { description: "[WT] Wire Transfer from Jennifer White", type: "Wire Transfer" },
  { description: "[PO] Food Lion Grocery", type: "Purchase" },
  { description: "[PM] Credit Card Payment - Wells Fargo", type: "Credit Card Payment" },
  { description: "[PO] Burger King", type: "Debit Card Purchase" },
  { description: "[DD] Bonus Deposit - ABC Corporation", type: "Direct Deposit" },
  { description: "[FE] Account Closure Fee", type: "Fee" },
  { description: "[PO] Petco Pet Supplies", type: "Purchase" },
  { description: "[WD] ATM Withdrawal - TD Bank", type: "ATM Withdrawal" },
  { description: "[RF] Refund from CVS Pharmacy", type: "Refund" },
  { description: "[PO] Aldi Grocery Store", type: "Debit Card Purchase" },
  { description: "[PO] Amazon Prime Subscription", type: "Purchase" },
  { description: "[TR] Transfer from Joint Account", type: "Transfer" },
  { description: "[PO] Papa John's Pizza", type: "Purchase" },
  { description: "[WD] Teller Withdrawal", type: "Withdrawal" },
  { description: "[PO] Bed Bath & Beyond", type: "Debit Card Purchase" },
  { description: "[DD] Payroll Deposit - Manufacturing LLC", type: "Direct Deposit" },
  { description: "[IN] Money Market Interest", type: "Interest" }
]
